import { readableTitle } from "@util/helpers";
import { groupBy } from "underscore";

export const BASE_URL = "https://www.googleapis.com/books/v1";

export const GENRES = [
  "algebra",
  "animals",
  "anthropology",
  "archaeology",
  "architecture",
  "art",
  "art_history",
  "art_instruction",
  "artists",
  "autobiographies",
  "baby_books",
  "bears",
  "bedtime_books",
  "biography",
  "biology",
  "brazil",
  "business",
  "business_&_finance",
  "business_economics",
  "business_success",
  "cats",
  "chemistry",
  "chick_lit",
  "children's",
  "christian",
  "classics",
  "comedy",
  "comics",
  "composers",
  "computer_science",
  "contemporary",
  "cookbooks",
  "cooking",
  "crime",
  "dance",
  "design",
  "dogs",
  "ebooks",
  "education",
  "english_language",
  "entrepreneurship",
  "exercise",
  "fantasy",
  "fashion",
  "fiction",
  "film",
  "finance",
  "geography",
  "graphic_design",
  "graphic_novels",
  "health_&_wellness",
  "historical_fiction",
  "history",
  "horror",
  "humor",
  "india",
  "indonesia",
  "kids_books",
  "kings_and_rulers",
  "kittens",
  "literature",
  "magic",
  "management",
  "manga",
  "mathematics",
  "memoir",
  "mental_health",
  "music",
  "music_theory",
  "mystery",
  "mystery_and_detective_stories",
  "nonfiction",
  "nutrition",
  "painting",
  "paranormal",
  "philosophy",
  "photography",
  "physics",
  "picture_books",
  "places",
  "plays",
  "poetry",
  "political_science",
  "politics_and_government",
  "programming",
  "psychology",
  "puppies",
  "religion",
  "romance",
  "science",
  "science_&_mathematics",
  "science_fiction",
  "self-help",
  "short_stories",
  "social_life_and_customs",
  "social_sciences",
  "spirituality",
  "sports",
  "stories_in_rhyme",
  "suspense",
  "textbooks",
  "thriller",
  "travel",
  "women",
  "world_war",
  "young_adult",
];

export const groupedGenres = groupBy(GENRES, (i) => i[0]);

export const GENRE_SUGGESTIONS = GENRES.map((g) => {
  return {
    value: g,
    name: readableTitle(g),
  };
});
